name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test with Bun on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: $HOME/.bun/bin/bun install

      - name: Lint
        run: $HOME/.bun/bin/bun run biome ci

      - name: Test
        run: $HOME/.bun/bin/bun test

      - name: Build
        run: npm run build
